# Generated by Django 6.0.5 on 2026-06-12 12:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('locations', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('projects', '0001_initial'),
        ('taxonomy', '0002_taxoncharacteristic_taxonrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable observation code, for example OBS-PLJ-001.', max_length=80, unique=True)),
                ('observation_type', models.CharField(choices=[('camera_trap', 'Camera trap'), ('direct_sighting', 'Direct sighting'), ('track_or_sign', 'Track or sign'), ('audio', 'Audio'), ('drone', 'Drone'), ('imported', 'Imported'), ('unknown', 'Unknown')], db_index=True, default='camera_trap', max_length=40)),
                ('observation_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=40)),
                ('verification_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('review_needed', 'Review needed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('uncertain', 'Uncertain')], db_index=True, default='unreviewed', max_length=40)),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Main timestamp when the observation was recorded or captured.')),
                ('observed_started_at', models.DateTimeField(blank=True, help_text='Optional start time when the observed event began.', null=True)),
                ('observed_ended_at', models.DateTimeField(blank=True, help_text='Optional end time when the observed event ended.', null=True)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('highly_sensitive', 'Highly sensitive'), ('critical', 'Critical')], db_index=True, default='normal', help_text='Conservation/privacy risk level. Sensitive data must be protected later by policy.', max_length=40)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted')], db_index=True, default='restricted', help_text='Audience-level visibility. Public exposure still requires safe selectors later.', max_length=40)),
                ('public_location_label_bs', models.CharField(blank=True, help_text='Bosnian public-safe location label. Do not put exact coordinates here.', max_length=255)),
                ('public_location_label_en', models.CharField(blank=True, help_text='English public-safe location label. Do not put exact coordinates here.', max_length=255)),
                ('public_location_precision', models.CharField(choices=[('none', 'No public location'), ('region', 'Region only'), ('location_zone', 'Location zone'), ('habitat', 'Habitat'), ('monitoring_point_generalized', 'Monitoring point generalized')], default='none', help_text='Controls how precise public location can be later.', max_length=60)),
                ('notes_public_bs', models.TextField(blank=True, help_text='Bosnian public-safe observation notes.')),
                ('notes_public_en', models.TextField(blank=True, help_text='English public-safe observation notes.')),
                ('notes_private', models.TextField(blank=True, help_text='Private internal notes. Never expose through public APIs later.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when this observation was verified by a human reviewer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_deployment', models.ForeignKey(blank=True, help_text='Camera deployment context if this observation came from a deployed camera.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='monitoring.cameradeployment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
                ('habitat', models.ForeignKey(blank=True, help_text='Habitat context for this observation, if known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='locations.habitat')),
                ('location_zone', models.ForeignKey(blank=True, help_text='General location zone for this observation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='locations.locationzone')),
                ('monitoring_point', models.ForeignKey(blank=True, help_text='Permanent monitoring point linked to this observation, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='locations.monitoringpoint')),
                ('project', models.ForeignKey(help_text='Project that owns this scientific observation.', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='projects.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ObservationEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('primary', 'Primary evidence'), ('supporting', 'Supporting evidence'), ('context', 'Context evidence'), ('disputed', 'Disputed evidence')], db_index=True, default='supporting', max_length=40)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Marks the main evidence item for this observation.')),
                ('notes', models.TextField(blank=True, help_text='Optional internal note explaining how this evidence supports the observation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_links', to='evidence.evidenceitem')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='observations.observation')),
            ],
            options={
                'ordering': ['-is_primary', 'link_type', 'evidence_item_id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('review_needed', 'Review needed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_more_evidence', 'Needs more evidence'), ('uncertain', 'Uncertain')], db_index=True, default='review_needed', max_length=40)),
                ('review_notes', models.TextField(blank=True, help_text='Internal review notes. Do not expose publicly later.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when this review decision was made.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='observations.observation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_status', models.CharField(choices=[('unknown', 'Unknown'), ('possible', 'Possible'), ('likely', 'Likely'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='unknown', max_length=40)),
                ('confidence_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('certain', 'Certain')], db_index=True, default='unknown', max_length=40)),
                ('life_stage', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('juvenile', 'Juvenile'), ('subadult', 'Subadult'), ('adult', 'Adult'), ('old', 'Old')], default='unknown', max_length=40)),
                ('sex', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed'), ('not_applicable', 'Not applicable')], default='unknown', max_length=40)),
                ('count_min', models.PositiveIntegerField(blank=True, help_text='Minimum observed count, if known.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('count_max', models.PositiveIntegerField(blank=True, help_text='Maximum observed count, if known.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('behavior_notes_bs', models.TextField(blank=True, help_text='Bosnian behavior notes for this taxon in the observation.')),
                ('behavior_notes_en', models.TextField(blank=True, help_text='English behavior notes for this taxon in the observation.')),
                ('identified_at', models.DateTimeField(blank=True, help_text='Timestamp when this identification was made or confirmed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_observation_taxa', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_links', to='observations.observation')),
                ('taxon', models.ForeignKey(blank=True, help_text='Canonical taxon identity. Can be blank for unknown observations if needed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_links', to='taxonomy.taxon')),
            ],
            options={
                'ordering': ['observation', 'taxon_id', '-confidence_level'],
            },
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['project', 'observation_status'], name='observation_project_d3e81c_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['project', 'verification_status'], name='observation_project_148fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['project', 'recorded_at'], name='observation_project_674ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['sensitivity_level', 'visibility_level'], name='observation_sensiti_9ba4e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationevidencelink',
            constraint=models.UniqueConstraint(fields=('observation', 'evidence_item'), name='unique_observation_evidence_link'),
        ),
        migrations.AddConstraint(
            model_name='observationevidencelink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('observation',), name='unique_primary_evidence_per_observation'),
        ),
        migrations.AddIndex(
            model_name='observationreview',
            index=models.Index(fields=['review_status', 'reviewed_at'], name='observation_review__377399_idx'),
        ),
        migrations.AddIndex(
            model_name='observationtaxon',
            index=models.Index(fields=['identification_status', 'confidence_level'], name='observation_identif_eeeebc_idx'),
        ),
        migrations.AddIndex(
            model_name='observationtaxon',
            index=models.Index(fields=['taxon', 'identification_status'], name='observation_taxon_i_9009bd_idx'),
        ),
    ]
