# Generated by Django 6.0.5 on 2026-06-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('verification_changed', 'Verification changed'), ('taxon_changed', 'Taxon changed'), ('evidence_changed', 'Evidence changed'), ('visibility_changed', 'Visibility changed'), ('sensitivity_changed', 'Sensitivity changed'), ('notes_changed', 'Notes changed'), ('scientific_correction', 'Scientific correction'), ('other', 'Other')], db_index=True, default='other', max_length=60)),
                ('reason', models.TextField(blank=True, help_text='Human explanation for why this revision was made.')),
                ('previous_observation_status', models.CharField(blank=True, help_text='Previous observation status before this revision.', max_length=60)),
                ('new_observation_status', models.CharField(blank=True, help_text='New observation status after this revision.', max_length=60)),
                ('previous_verification_status', models.CharField(blank=True, help_text='Previous verification status before this revision.', max_length=60)),
                ('new_verification_status', models.CharField(blank=True, help_text='New verification status after this revision.', max_length=60)),
                ('previous_taxon_summary', models.CharField(blank=True, help_text='Short summary of previous taxon interpretation.', max_length=255)),
                ('new_taxon_summary', models.CharField(blank=True, help_text='Short summary of new taxon interpretation.', max_length=255)),
                ('previous_visibility_level', models.CharField(blank=True, help_text='Previous visibility level before this revision.', max_length=60)),
                ('new_visibility_level', models.CharField(blank=True, help_text='New visibility level after this revision.', max_length=60)),
                ('previous_sensitivity_level', models.CharField(blank=True, help_text='Previous sensitivity level before this revision.', max_length=60)),
                ('new_sensitivity_level', models.CharField(blank=True, help_text='New sensitivity level after this revision.', max_length=60)),
                ('notes', models.TextField(blank=True, help_text='Internal revision notes. Do not expose publicly later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made or recorded this revision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_revisions', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(help_text='Observation whose scientific/history record changed.', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='observations.observation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['observation', 'revision_type'], name='observation_observa_12ae46_idx'), models.Index(fields=['revision_type', 'created_at'], name='observation_revisio_ec8ce0_idx')],
            },
        ),
    ]
