# Generated by Django 6.0.5 on 2026-06-11 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name_bs', models.CharField(max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('monitoring', 'Monitoring'), ('species_survey', 'Species survey'), ('fungi_survey', 'Fungi survey'), ('plant_survey', 'Plant survey'), ('drone_survey', 'Drone survey'), ('camera_network', 'Camera network'), ('research', 'Research'), ('education', 'Education'), ('sponsor_program', 'Sponsor program'), ('grant_program', 'Grant program'), ('other', 'Other')], default='monitoring', max_length=40)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=30)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted')], default='restricted', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('owning_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='organizations.organization')),
            ],
            options={
                'ordering': ['name_bs'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('collaboration_role', models.CharField(choices=[('research_partner', 'Research partner'), ('field_partner', 'Field partner'), ('funding_partner', 'Funding partner'), ('government_partner', 'Government partner'), ('ngo_partner', 'NGO partner'), ('university_partner', 'University partner'), ('sponsor_partner', 'Sponsor partner'), ('observer', 'Observer'), ('other', 'Other')], default='other', max_length=40)),
                ('access_level', models.CharField(choices=[('public_safe', 'Public safe'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted')], default='public_safe', max_length=30)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], default='invited', max_length=30)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_collaborations', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='projects.project')),
            ],
            options={
                'ordering': ['project__name_bs', 'organization__name'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owning_organization', 'status'], name='projects_pr_owning__6b2e09_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'status'], name='projects_pr_project_9d76d4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visibility_level'], name='projects_pr_visibil_cb28ff_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_800144_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_4b0cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['collaboration_role'], name='projects_pr_collabo_b482b1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcollaboration',
            index=models.Index(fields=['access_level'], name='projects_pr_access__151d4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcollaboration',
            constraint=models.UniqueConstraint(fields=('project', 'organization'), name='unique_project_collaboration_per_organization'),
        ),
    ]
