# Generated by Django 6.0.5 on 2026-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/originals/'),
        ),
    ]
