# Generated by Django 6.0.5 on 2026-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_mediaitem_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description_bs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_description_bs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_title_bs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='title_bs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='alt_text_bs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='caption_bs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='caption_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description_bs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='title_bs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
