# Generated by Django 6.0.5 on 2026-05-30 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_copy_content_to_en_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['display_order', 'title_en', 'title']},
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bs', models.CharField(blank=True, max_length=200)),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_bs', models.TextField(blank=True)),
                ('body_en', models.TextField()),
                ('body_bs', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_field_notes', to='gallery.mediaitem')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
