# Generated by Django 6.0.5 on 2026-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_album_options_fieldnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='original_file',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/originals/'),
        ),
    ]
