# Generated by Django 6.0.5 on 2026-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_album_title_alter_mediaitem_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='provider',
            field=models.CharField(choices=[('local', 'Local'), ('cloudinary', 'Cloudinary'), ('cloudflare_images', 'Cloudflare Images'), ('cloudflare_stream', 'Cloudflare Stream')], default='local', max_length=20),
        ),
    ]
