# Generated by Django 6.0.5 on 2026-06-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_mediaitem_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bs', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cloudflare_uid', models.CharField(max_length=128, unique=True)),
                ('cloudflare_thumbnail_url', models.URLField(blank=True)),
                ('cloudflare_playback_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='gallery.album')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
