# Generated by Django 6.0.5 on 2026-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_album_gallery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bs', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='albums', to='gallery.tag'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='video_clips', to='gallery.tag'),
        ),
    ]
