# Generated by Django 6.0.5 on 2026-06-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_visitor_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormessage',
            name='timestamp_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_messages', to='gallery.videoclip'),
        ),
        migrations.AddIndex(
            model_name='visitormessage',
            index=models.Index(fields=['status'], name='gallery_vis_status_e6d21c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormessage',
            index=models.Index(fields=['created_at'], name='gallery_vis_created_ebd9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormessage',
            index=models.Index(fields=['sender_email'], name='gallery_vis_sender__69f4a6_idx'),
        ),
    ]
