# Generated by Django 6.0.5 on 2026-06-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_visitor_message_video_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTimestampComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('timestamp_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamp_comments', to='gallery.videoclip')),
            ],
            options={
                'ordering': ['timestamp_seconds', 'created_at'],
                'indexes': [models.Index(fields=['video', 'status'], name='gallery_vid_video_i_61b339_idx'), models.Index(fields=['status'], name='gallery_vid_status_8ee845_idx'), models.Index(fields=['created_at'], name='gallery_vid_created_a99bb7_idx')],
            },
        ),
    ]
