# Generated by Django 6.0.5 on 2026-06-05 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_video_timestamp_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VisitorMessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_subject', models.CharField(max_length=250)),
                ('reply_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_message_replies', to=settings.AUTH_USER_MODEL)),
                ('visitor_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gallery.visitormessage')),
            ],
            options={
                'verbose_name': 'Visitor Message Reply',
                'verbose_name_plural': 'Visitor Message Replies',
                'ordering': ['-sent_at'],
            },
        ),
    ]
