# Generated by Django 6.0.5 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_visitor_message_replied_at_reply_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['is_public', 'status', '-created_at', '-id'], name='video_pub_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['album', 'is_public', 'status', '-created_at', '-id'], name='video_album_public_created_idx'),
        ),
    ]
