# Generated by Django 6.0.5 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_admin_notification_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotimestampcomment',
            name='text_bs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videotimestampcomment',
            name='translation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videotimestampcomment',
            name='translation_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='message_bs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='subject_bs',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='translation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='translation_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
