# Generated by Django 6.0.5 on 2026-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_visitor_message_reply_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_error_reason_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_error_reason_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_pct_complete',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_status_state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='cloudflare_status_step',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='processing_warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='submitted_title_bs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='title_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('backend_auto', 'Backend auto-generated'), ('filename', 'Derived from filename'), ('cloudflare', 'Cloudflare metadata'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
