# Generated by Django 6.0.5 on 2026-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_videoclip_upload_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('location', 'Location'), ('species', 'Species'), ('habitat', 'Habitat'), ('behavior', 'Behavior'), ('content_type', 'Content Type'), ('general', 'General')], db_index=True, default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_bs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='gallery.tag'),
        ),
    ]
