# Generated by Django 6.0.5 on 2026-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_analytics_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldnote',
            old_name='location',
            new_name='location_bs',
        ),
        migrations.AddField(
            model_name='fieldnote',
            name='location_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldnote',
            name='body_bs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fieldnote',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldnote',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldnote',
            name='title_bs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldnote',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='fieldnote',
            index=models.Index(fields=['is_published', '-published_at'], name='gallery_fie_is_publ_a476e6_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldnote',
            index=models.Index(fields=['slug'], name='gallery_fie_slug_404f3c_idx'),
        ),
    ]
