# Generated by Django 6.0.5 on 2026-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_rename_location_fieldnote_location_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='original_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='original_extension',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='original_file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
