# Generated by Django 6.0.5 on 2026-06-11 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('taxon_rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species'), ('subspecies', 'Subspecies'), ('group', 'Group'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('taxon_group', models.CharField(choices=[('animal', 'Animal'), ('mammal', 'Mammal'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('insect', 'Insect'), ('plant', 'Plant'), ('tree', 'Tree'), ('flower', 'Flower'), ('fungus', 'Fungus'), ('mushroom', 'Mushroom'), ('moss', 'Moss'), ('lichen', 'Lichen'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('scientific_name_current', models.CharField(blank=True, max_length=220)),
                ('canonical_display_name_bs', models.CharField(max_length=220)),
                ('canonical_display_name_en', models.CharField(blank=True, max_length=220)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('identification_notes_bs', models.TextField(blank=True)),
                ('identification_notes_en', models.TextField(blank=True)),
                ('native_status', models.CharField(choices=[('native', 'Native'), ('introduced', 'Introduced'), ('invasive', 'Invasive'), ('reintroduced', 'Reintroduced'), ('uncertain', 'Uncertain'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('highly_sensitive', 'Highly sensitive'), ('critical', 'Critical')], default='normal', max_length=30)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_taxa', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name_plural': 'Taxa',
                'ordering': ['canonical_display_name_bs'],
            },
        ),
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_type', models.CharField(choices=[('global', 'Global'), ('local', 'Local'), ('national', 'National'), ('regional', 'Regional'), ('legal', 'Legal'), ('project_specific', 'Project specific')], default='local', max_length=40)),
                ('status_value', models.CharField(choices=[('least_concern', 'Least concern'), ('near_threatened', 'Near threatened'), ('vulnerable', 'Vulnerable'), ('endangered', 'Endangered'), ('critically_endangered', 'Critically endangered'), ('extinct_in_wild', 'Extinct in wild'), ('extinct', 'Extinct'), ('data_deficient', 'Data deficient'), ('not_evaluated', 'Not evaluated'), ('protected', 'Protected'), ('strictly_protected', 'Strictly protected'), ('hunting_allowed', 'Hunting allowed'), ('seasonal_protection', 'Seasonal protection'), ('conservation_priority', 'Conservation priority')], default='not_evaluated', max_length=50)),
                ('jurisdiction', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_statuses', to='taxonomy.taxon')),
            ],
            options={
                'ordering': ['taxon__canonical_display_name_bs', 'status_type', 'status_value'],
            },
        ),
        migrations.CreateModel(
            name='TaxonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('name_type', models.CharField(choices=[('scientific_name', 'Scientific name'), ('common_name_bs', 'Common name BS'), ('common_name_en', 'Common name EN'), ('local_name', 'Local name'), ('historical_name', 'Historical name'), ('government_name', 'Government name'), ('research_name', 'Research name'), ('synonym', 'Synonym'), ('deprecated_name', 'Deprecated name')], default='common_name_bs', max_length=40)),
                ('language_code', models.CharField(blank=True, max_length=12)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='taxonomy.taxon')),
            ],
            options={
                'ordering': ['taxon__canonical_display_name_bs', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['code'], name='taxonomy_ta_code_612b96_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['slug'], name='taxonomy_ta_slug_21ea45_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['taxon_group', 'taxon_rank'], name='taxonomy_ta_taxon_g_3292fb_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['is_sensitive'], name='taxonomy_ta_is_sens_a21ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['is_published'], name='taxonomy_ta_is_publ_ac4083_idx'),
        ),
        migrations.AddIndex(
            model_name='conservationstatus',
            index=models.Index(fields=['status_type'], name='taxonomy_co_status__d22b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='conservationstatus',
            index=models.Index(fields=['status_value'], name='taxonomy_co_status__6e640c_idx'),
        ),
        migrations.AddIndex(
            model_name='conservationstatus',
            index=models.Index(fields=['jurisdiction'], name='taxonomy_co_jurisdi_d63eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonname',
            index=models.Index(fields=['name'], name='taxonomy_ta_name_ed7e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonname',
            index=models.Index(fields=['name_type'], name='taxonomy_ta_name_ty_ca8c16_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonname',
            index=models.Index(fields=['language_code'], name='taxonomy_ta_languag_81f9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonname',
            index=models.Index(fields=['is_primary'], name='taxonomy_ta_is_prim_cda4b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonname',
            constraint=models.UniqueConstraint(fields=('taxon', 'name', 'name_type', 'language_code'), name='unique_taxon_name_per_type_language'),
        ),
    ]
