# Generated by Django 6.0.5 on 2026-06-11 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('characteristic_type', models.CharField(choices=[('average_weight', 'Average weight'), ('minimum_weight', 'Minimum weight'), ('maximum_weight', 'Maximum weight'), ('average_length', 'Average length'), ('height', 'Height'), ('wingspan', 'Wingspan'), ('coloration', 'Coloration'), ('lifespan', 'Lifespan'), ('gestation_period', 'Gestation period'), ('offspring_count', 'Offspring count'), ('breeding_season', 'Breeding season'), ('sexual_maturity', 'Sexual maturity'), ('activity_pattern', 'Activity pattern'), ('social_behavior', 'Social behavior'), ('migration_behavior', 'Migration behavior'), ('territorial_behavior', 'Territorial behavior'), ('diet', 'Diet'), ('predators', 'Predators'), ('prey', 'Prey'), ('preferred_habitats', 'Preferred habitats'), ('elevation_range', 'Elevation range'), ('climate_preferences', 'Climate preferences'), ('threats', 'Threats'), ('protection_measures', 'Protection measures'), ('identification_notes', 'Identification notes'), ('taxonomic_notes', 'Taxonomic notes'), ('known_variations', 'Known variations'), ('other', 'Other')], default='other', max_length=60)),
                ('value_text_bs', models.TextField(blank=True)),
                ('value_text_en', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted')], default='public', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name': 'Taxon characteristic',
                'verbose_name_plural': 'Taxon characteristics',
                'ordering': ['taxon__canonical_display_name_bs', 'characteristic_type'],
                'indexes': [models.Index(fields=['characteristic_type'], name='taxonomy_ta_charact_cbae6b_idx'), models.Index(fields=['confidence_level'], name='taxonomy_ta_confide_f72421_idx'), models.Index(fields=['visibility_level'], name='taxonomy_ta_visibil_8fadf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('predator_of', 'Predator of'), ('prey_of', 'Prey of'), ('pollinates', 'Pollinates'), ('pollinated_by', 'Pollinated by'), ('host_of', 'Host of'), ('parasite_of', 'Parasite of'), ('symbiotic_with', 'Symbiotic with'), ('associated_with', 'Associated with'), ('competes_with', 'Competes with'), ('feeds_on', 'Feeds on'), ('depends_on', 'Depends on'), ('supports_habitat_for', 'Supports habitat for'), ('disperses_seeds_for', 'Disperses seeds for'), ('other', 'Other')], default='other', max_length=60)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_taxon_relationships', to='taxonomy.taxon')),
                ('target_taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_taxon_relationships', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name': 'Taxon relationship',
                'verbose_name_plural': 'Taxon relationships',
                'ordering': ['source_taxon__canonical_display_name_bs', 'relationship_type', 'target_taxon__canonical_display_name_bs'],
                'indexes': [models.Index(fields=['relationship_type'], name='taxonomy_ta_relatio_e8d0c1_idx'), models.Index(fields=['confidence_level'], name='taxonomy_ta_confide_f75c2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_taxon', 'target_taxon', 'relationship_type'), name='unique_taxon_relationship_type')],
            },
        ),
    ]
