# Generated by Django 6.0.5 on 2026-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_taxoncharacteristic_taxonrelationship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taxonname',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('taxon', 'name_type', 'language_code'), name='unique_primary_taxon_name_per_type_language'),
        ),
    ]
