"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ["SECRET_KEY"]  # Required — set in .env (copy .env.example)

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,kata-wild-backend-5b989da54ce2.herokuapp.com",
    ).split(",")
    if host.strip()
]

# CSRF trusted origins — required when frontend runs on a different origin or HTTPS.
# Defaults to local Vite dev server; override via env in production.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173"
        ",https://kata-photos.netlify.app"
        ",https://kata-wild-backend-5b989da54ce2.herokuapp.com",
    ).split(",")
    if origin.strip()
]

# CORS — allow local Vite frontend to call this API.
# Override via CORS_ALLOWED_ORIGINS env var in production.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173"
        ",https://kata-photos.netlify.app",
    ).split(",")
    if origin.strip()
]

# Allow the browser to send session cookies on cross-origin requests
# (required for session-based auth from the Vite frontend).
CORS_ALLOW_CREDENTIALS = True

# Cross-site session cookies — required for production where the frontend
# (https://kataphotos.com) and backend (Heroku) are on different sites.
# SameSite=None; Secure is required for credentialed cross-origin fetch().
# Defaults keep local dev working over plain HTTP with SameSite=Lax.
# On Heroku set: SESSION_COOKIE_SAMESITE=None, CSRF_COOKIE_SAMESITE=None,
#                SESSION_COOKIE_SECURE=True, CSRF_COOKIE_SECURE=True
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False").lower() == "true"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',

    "gallery",
    # Kata Wild canonical apps
    "audit.apps.AuditConfig",
    "organizations.apps.OrganizationsConfig",
    "access.apps.AccessConfig",
    "projects.apps.ProjectsConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Locally (no DATABASE_URL set): falls back to SQLite.
# On Heroku (DATABASE_URL set by Postgres add-on): uses PostgreSQL with SSL.
_DATABASE_URL = os.getenv("DATABASE_URL", "")
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=bool(_DATABASE_URL),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / "media"

# Primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudflare Images — set both in .env to enable cloud uploads.
# Leave empty to fall back to local storage.
CLOUDFLARE_ACCOUNT_ID = os.getenv("CLOUDFLARE_ACCOUNT_ID", "")
CLOUDFLARE_IMAGES_API_TOKEN = os.getenv("CLOUDFLARE_IMAGES_API_TOKEN", "")

# Cloudflare Stream — set to enable video direct-upload.
# CLOUDFLARE_ACCOUNT_ID is shared with Images above.
# Leave empty; a clear error is raised when Stream upload is attempted without config.
CLOUDFLARE_STREAM_API_TOKEN = os.getenv("CLOUDFLARE_STREAM_API_TOKEN", "")
CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN = os.getenv("CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN", "")
CLOUDFLARE_STREAM_DIRECT_UPLOAD_EXPIRY_SECONDS = int(
    os.getenv("CLOUDFLARE_STREAM_DIRECT_UPLOAD_EXPIRY_SECONDS", "3600")
)
# Optional: burned-in watermark profile UID applied to every new direct upload.
# Leave empty to upload without a watermark.
CLOUDFLARE_STREAM_WATERMARK_UID = os.getenv("CLOUDFLARE_STREAM_WATERMARK_UID", "")

# ---------------------------------------------------------------------------
# OpenAI — auto-translation (Bosnian → English)
# ---------------------------------------------------------------------------
# Set OPENAI_API_KEY via Heroku config vars or .env (never commit the key).
# OPENAI_TRANSLATION_MODEL is optional; defaults to gpt-4o-mini in the service.
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_TRANSLATION_MODEL = os.getenv("OPENAI_TRANSLATION_MODEL", "")

# ---------------------------------------------------------------------------
# Social sharing
# ---------------------------------------------------------------------------
# Public frontend root — used to build frontend_url in share API responses.
FRONTEND_URL = os.getenv("FRONTEND_URL", "https://kataphotos.com")
# Fallback OG image for share pages when no media is available.
# Set to an absolute HTTPS URL of a static image on the frontend or CDN.
FALLBACK_OG_IMAGE = os.getenv("FALLBACK_OG_IMAGE", "")

# ---------------------------------------------------------------------------
# Email — Django built-in mail system
# ---------------------------------------------------------------------------
# For local/dev testing set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# (the default below) so email is printed to the console without an SMTP server.
# For production set all variables via environment:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.example.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_USE_SSL=False
#   EMAIL_HOST_USER=sender@example.com
#   EMAIL_HOST_PASSWORD=<secret — never commit>
#   DEFAULT_FROM_EMAIL=sender@example.com
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")
