# Generated by Django 6.0.5 on 2026-06-10 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_label', models.CharField(blank=True, help_text='Snapshot label of the actor at the time of action, for example username/email.', max_length=255)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('status_changed', 'Status changed'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('revised', 'Revised'), ('access_granted', 'Access granted'), ('access_revoked', 'Access revoked'), ('role_assigned', 'Role assigned'), ('role_removed', 'Role removed'), ('capability_assigned', 'Capability assigned'), ('capability_removed', 'Capability removed'), ('permission_changed', 'Permission changed'), ('sensitive_data_viewed', 'Sensitive data viewed'), ('private_coordinates_viewed', 'Private coordinates viewed'), ('private_geometry_viewed', 'Private geometry viewed'), ('restricted_record_viewed', 'Restricted record viewed'), ('evidence_linked', 'Evidence linked'), ('evidence_unlinked', 'Evidence unlinked'), ('export_generated', 'Export generated'), ('export_downloaded', 'Export downloaded'), ('ai_suggestion_reviewed', 'AI suggestion reviewed'), ('internal_workflow_ran', 'Internal workflow ran'), ('system_configuration_changed', 'System configuration changed')], db_index=True, max_length=80)),
                ('target_object_type', models.CharField(db_index=True, help_text='Canonical target type, for example Observation, Project, Taxon.', max_length=120)),
                ('target_object_id', models.CharField(blank=True, db_index=True, help_text='Target primary key, UUID, permanent code, or external identifier.', max_length=120)),
                ('acting_membership_id', models.CharField(blank=True, help_text='Membership context used for the action, when available.', max_length=120)),
                ('organization_id', models.CharField(blank=True, db_index=True, help_text='Acting organization or organization scope, when available.', max_length=120)),
                ('project_id', models.CharField(blank=True, db_index=True, help_text='Project scope, when available.', max_length=120)),
                ('scope', models.CharField(blank=True, help_text='Optional human-readable scope, for example project:PRJ-000001.', max_length=160)),
                ('capability_used', models.CharField(blank=True, help_text='Capability used to authorize the action, when applicable.', max_length=120)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('sensitivity_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=40)),
                ('contains_sensitive_data', models.BooleanField(default=False, help_text='True when the action involved sensitive/protected data.')),
                ('contains_private_coordinates', models.BooleanField(default=False, help_text='True when exact/private coordinates were viewed or exported.')),
                ('contains_restricted_fields', models.BooleanField(default=False, help_text='True when restricted fields were viewed, changed, or exported.')),
                ('before_snapshot', models.JSONField(blank=True, help_text='Optional compact snapshot before the action.', null=True)),
                ('after_snapshot', models.JSONField(blank=True, help_text='Optional compact snapshot after the action.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional structured context, such as export privacy mode or request source.', null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Optional request/correlation ID for tracing one request across logs.', max_length=120)),
                ('reason', models.TextField(blank=True, help_text='Reason supplied by actor, reviewer, admin, or workflow.')),
                ('note', models.TextField(blank=True, help_text='Internal audit note.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null is allowed for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit record',
                'verbose_name_plural': 'Audit records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_5e0549_idx'), models.Index(fields=['action_type', 'created_at'], name='audit_audit_action__198509_idx'), models.Index(fields=['target_object_type', 'target_object_id'], name='audit_audit_target__39e772_idx'), models.Index(fields=['organization_id', 'created_at'], name='audit_audit_organiz_7e1997_idx'), models.Index(fields=['project_id', 'created_at'], name='audit_audit_project_8bf384_idx'), models.Index(fields=['request_id', 'created_at'], name='audit_audit_request_d6925c_idx'), models.Index(fields=['contains_sensitive_data', 'created_at'], name='audit_audit_contain_6363dc_idx'), models.Index(fields=['contains_private_coordinates', 'created_at'], name='audit_audit_contain_3c5327_idx'), models.Index(fields=['contains_restricted_fields', 'created_at'], name='audit_audit_contain_6debec_idx')],
            },
        ),
    ]
