# Generated by Django 6.0.5 on 2026-06-11 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0002_membership_role'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('purchased', 'Purchased'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('broken', 'Broken'), ('lost', 'Lost'), ('retired', 'Retired'), ('archived', 'Archived')], default='planned', max_length=30)),
                ('notes_private', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_cameras', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CameraDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('retired', 'Retired'), ('archived', 'Archived')], default='planned', max_length=30)),
                ('deployment_notes', models.TextField(blank=True)),
                ('public_description_bs', models.TextField(blank=True)),
                ('public_description_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='monitoring.camera')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_camera_deployments', to=settings.AUTH_USER_MODEL)),
                ('monitoring_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camera_deployments', to='locations.monitoringpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camera_deployments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Camera deployment',
                'verbose_name_plural': 'Camera deployments',
                'ordering': ['-started_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CameraMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('maintenance_type', models.CharField(choices=[('battery_replacement', 'Battery replacement'), ('memory_card_replacement', 'Memory card replacement'), ('lens_cleaning', 'Lens cleaning'), ('firmware_update', 'Firmware update'), ('physical_repair', 'Physical repair'), ('inspection', 'Inspection'), ('relocation_check', 'Relocation check'), ('damage_report', 'Damage report'), ('other', 'Other')], default='inspection', max_length=40)),
                ('performed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('battery_changed', models.BooleanField(default=False)),
                ('memory_card_changed', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('issue_detected', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='monitoring.camera')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='monitoring.cameradeployment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_camera_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera maintenance record',
                'verbose_name_plural': 'Camera maintenance records',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['code'], name='monitoring__code_2f3ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['ownership_organization', 'status'], name='monitoring__ownersh_bea12e_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status'], name='monitoring__status_dd1a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['serial_number'], name='monitoring__serial__68c1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['code'], name='monitoring__code_a94184_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['project', 'status'], name='monitoring__project_c9b112_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['camera', 'status'], name='monitoring__camera__3c0b34_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['monitoring_point', 'status'], name='monitoring__monitor_7ebf53_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['started_at'], name='monitoring__started_82c7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cameradeployment',
            index=models.Index(fields=['ended_at'], name='monitoring__ended_a_93904e_idx'),
        ),
        migrations.AddIndex(
            model_name='cameramaintenancerecord',
            index=models.Index(fields=['camera', 'performed_at'], name='monitoring__camera__0d9757_idx'),
        ),
        migrations.AddIndex(
            model_name='cameramaintenancerecord',
            index=models.Index(fields=['deployment', 'performed_at'], name='monitoring__deploym_b8e3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='cameramaintenancerecord',
            index=models.Index(fields=['maintenance_type'], name='monitoring__mainten_c1a0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cameramaintenancerecord',
            index=models.Index(fields=['performed_at'], name='monitoring__perform_2aa593_idx'),
        ),
    ]
