# Generated by Django 6.0.5 on 2026-06-12 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('projects', '0001_initial'),
        ('taxonomy', '0002_taxoncharacteristic_taxonrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Stable backend evidence code, for example EVD-PLJ-001.', max_length=80, unique=True)),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('field_note', 'Field note'), ('sensor_record', 'Sensor record'), ('drone_media', 'Drone media'), ('other', 'Other')], default='video', max_length=40)),
                ('source_type', models.CharField(choices=[('trail_camera', 'Trail camera'), ('manual_upload', 'Manual upload'), ('field_observer', 'Field observer'), ('drone', 'Drone'), ('sensor', 'Sensor'), ('archive', 'Archive'), ('other', 'Other')], default='trail_camera', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review_needed', 'Review needed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='submitted', max_length=40)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('restricted', 'Restricted')], default='normal', max_length=40)),
                ('visibility_level', models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('research', 'Research'), ('public_safe', 'Public safe')], default='private', max_length=40)),
                ('capture_started_at', models.DateTimeField(blank=True, help_text='Optional start time when the evidence capture began.', null=True)),
                ('capture_ended_at', models.DateTimeField(blank=True, help_text='Optional end time when the evidence capture ended.', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Main recorded timestamp if only one timestamp is known.', null=True)),
                ('title_bs', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('notes_private', models.TextField(blank=True, help_text='Private internal notes. Never expose this in public APIs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_deployment', models.ForeignKey(blank=True, help_text='Optional deployment active when this evidence was captured.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='monitoring.cameradeployment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/submitted this evidence record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_items', to=settings.AUTH_USER_MODEL)),
                ('monitoring_point', models.ForeignKey(blank=True, help_text='Optional permanent monitoring point where this evidence was captured.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='locations.monitoringpoint')),
                ('project', models.ForeignKey(help_text='Project that owns this evidence record.', on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'Evidence item',
                'verbose_name_plural': 'Evidence items',
                'ordering': ['-recorded_at', '-capture_started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('metadata', 'Metadata'), ('other', 'Other')], default='video', max_length=40)),
                ('storage_provider', models.CharField(choices=[('cloudinary', 'Cloudinary'), ('cloudflare_stream', 'Cloudflare Stream'), ('s3', 'S3-compatible storage'), ('local_archive', 'Local archive'), ('external_url', 'External URL'), ('manual_reference', 'Manual reference'), ('other', 'Other')], default='manual_reference', max_length=60)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename if known.', max_length=255)),
                ('storage_key', models.CharField(blank=True, help_text='Provider-specific storage key, public ID, UID, object key, or archive reference.', max_length=500)),
                ('external_url', models.URLField(blank=True, help_text='Optional external URL when file is referenced by URL.', max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes if known.', null=True)),
                ('checksum', models.CharField(blank=True, help_text='Optional checksum for future duplicate/integrity validation.', max_length=128)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Duration for video/audio evidence files.', max_digits=10, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the main file/preview for this evidence item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='evidence.evidenceitem')),
            ],
            options={
                'verbose_name': 'Evidence file',
                'verbose_name_plural': 'Evidence files',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceTaxonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identification_status', models.CharField(choices=[('possible', 'Possible'), ('likely', 'Likely'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='possible', max_length=40)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('expert_confirmed', 'Expert confirmed')], default='medium', max_length=40)),
                ('identified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes explaining why this taxon identification was suggested.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_links', to='evidence.evidenceitem')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_evidence_taxa', to=settings.AUTH_USER_MODEL)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name': 'Evidence taxon link',
                'verbose_name_plural': 'Evidence taxon links',
                'ordering': ['taxon__canonical_display_name_bs', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['project', 'status'], name='evidence_ev_project_caaa32_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['evidence_type', 'status'], name='evidence_ev_evidenc_0a42e6_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['sensitivity_level', 'visibility_level'], name='evidence_ev_sensiti_c62f20_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['recorded_at'], name='evidence_ev_recorde_01e21a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['capture_started_at'], name='evidence_ev_capture_8d62e8_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['evidence_item', 'file_type'], name='evidence_ev_evidenc_c13dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['storage_provider'], name='evidence_ev_storage_d503bc_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['checksum'], name='evidence_ev_checksu_dbc6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['is_primary'], name='evidence_ev_is_prim_ae2123_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencetaxonlink',
            index=models.Index(fields=['evidence_item', 'identification_status'], name='evidence_ev_evidenc_7be1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencetaxonlink',
            index=models.Index(fields=['taxon', 'confidence_level'], name='evidence_ev_taxon_i_7485fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencetaxonlink',
            constraint=models.UniqueConstraint(fields=('evidence_item', 'taxon'), name='unique_taxon_per_evidence_item'),
        ),
    ]
