# Generated by Django 6.0.5 on 2026-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidencefile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('evidence_item',), name='unique_primary_file_per_evidence_item'),
        ),
    ]
