# Generated by Django 6.0.5 on 2026-06-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='access.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='access.role')),
            ],
            options={
                'verbose_name': 'Role capability',
                'verbose_name_plural': 'Role capabilities',
                'ordering': ['role__code', 'capability__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_role_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='unique_capability_per_role'),
        ),
    ]
