# Generated by Django 6.0.5 on 2026-06-11 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name_bs', models.CharField(max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('habitat_type', models.CharField(choices=[('forest', 'Forest'), ('river', 'River'), ('wetland', 'Wetland'), ('mountain', 'Mountain'), ('grassland', 'Grassland'), ('rocky_terrain', 'Rocky terrain'), ('meadow', 'Meadow'), ('canyon', 'Canyon'), ('human_adjacent', 'Human adjacent'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_habitats', to='locations.habitat')),
            ],
            options={
                'verbose_name': 'Habitat',
                'verbose_name_plural': 'Habitats',
                'ordering': ['name_bs'],
            },
        ),
        migrations.CreateModel(
            name='LocationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name_bs', models.CharField(max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('zone_type', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('area', 'Area'), ('sub_area', 'Sub area'), ('zone', 'Zone'), ('corridor', 'Corridor'), ('habitat_area', 'Habitat area'), ('river_basin', 'River basin'), ('mountain_sector', 'Mountain sector'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('public_label_bs', models.CharField(blank=True, max_length=180)),
                ('public_label_en', models.CharField(blank=True, max_length=180)),
                ('description_bs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('public_geometry', models.JSONField(blank=True, null=True)),
                ('private_geometry', models.JSONField(blank=True, null=True)),
                ('public_center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('public_center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('private_center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('private_center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('precision_level', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('generalized', 'Generalized'), ('region_only', 'Region only'), ('hidden', 'Hidden')], default='generalized', max_length=30)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('highly_sensitive', 'Highly sensitive'), ('critical', 'Critical')], default='normal', max_length=30)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner'), ('research', 'Research'), ('restricted', 'Restricted')], default='public', max_length=30)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_zones', to='locations.locationzone')),
            ],
            options={
                'verbose_name': 'Location zone',
                'verbose_name_plural': 'Location zones',
                'ordering': ['name_bs'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name_bs', models.CharField(max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('purpose', models.TextField(blank=True)),
                ('private_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('private_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('public_location_label_bs', models.CharField(blank=True, max_length=180)),
                ('public_location_label_en', models.CharField(blank=True, max_length=180)),
                ('public_location_precision', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('generalized', 'Generalized'), ('zone_only', 'Zone only'), ('hidden', 'Hidden')], default='generalized', max_length=30)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('highly_sensitive', 'Highly sensitive'), ('critical', 'Critical')], default='normal', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('archived', 'Archived')], default='planned', max_length=30)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('retired_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='locations.locationzone')),
                ('primary_habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='locations.habitat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_points', to='projects.project')),
            ],
            options={
                'verbose_name': 'Monitoring point',
                'verbose_name_plural': 'Monitoring points',
                'ordering': ['project__name_bs', 'name_bs'],
            },
        ),
        migrations.AddIndex(
            model_name='habitat',
            index=models.Index(fields=['code'], name='locations_h_code_d62c33_idx'),
        ),
        migrations.AddIndex(
            model_name='habitat',
            index=models.Index(fields=['slug'], name='locations_h_slug_1bcb32_idx'),
        ),
        migrations.AddIndex(
            model_name='habitat',
            index=models.Index(fields=['habitat_type'], name='locations_h_habitat_63bdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='habitat',
            index=models.Index(fields=['is_published'], name='locations_h_is_publ_a6231a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['code'], name='locations_l_code_2e9b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['slug'], name='locations_l_slug_ef27ae_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['zone_type'], name='locations_l_zone_ty_4bd3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['visibility_level'], name='locations_l_visibil_d25176_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['sensitivity_level'], name='locations_l_sensiti_5ab26a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationzone',
            index=models.Index(fields=['is_public'], name='locations_l_is_publ_afeab9_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['code'], name='locations_m_code_4856d1_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['slug'], name='locations_m_slug_d2d4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['project', 'status'], name='locations_m_project_a07611_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['location_zone', 'status'], name='locations_m_locatio_0cc910_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['primary_habitat'], name='locations_m_primary_c109d3_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringpoint',
            index=models.Index(fields=['sensitivity_level'], name='locations_m_sensiti_d281d9_idx'),
        ),
    ]
